# Generated by Django 3.0.7 on 2023-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='/', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
