# Generated by Django 3.0.7 on 2023-06-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='wallet_address',
            field=models.CharField(default='0x99bc949975C4bd87D2a6d2a5043112C121EC68D1', max_length=200),
            preserve_default=False,
        ),
    ]
